### PR TITLE
add parallel to polkadot crowdloan

### PR DESCRIPTION
**Pull request by GopherJ**

### CODE REVIEW

**Comment by GopherJ** [comment]
hi, let us know if this is good now, thanks

**Comment by tarmovannas** [comment]
> hi, let us know if this is good now, thanks

for icon could you change it to this please:
`https://raw.githubusercontent.com/soramitsu/fearless-utils/master/crowdloan/icons/parallelfinance.png`

**Comment by GopherJ** [comment]
> > hi, let us know if this is good now, thanks
> 
> for icon could you change it to this please: `https://raw.githubusercontent.com/soramitsu/fearless-utils/master/crowdloan/icons/parallelfinance.png`

done

**Comment by GopherJ** [comment]
@tarmovannas I think the icon is not good :

image

**Comment by tarmovannas** [comment]
moonbea Parachain Crowdloans

we have icons in white, the png has a transparent background, it will look similar to the mockup above

**Review by tarmovannas — APPROVED** [review]

**Comment by GopherJ** [comment]
@tarmovannas but will it work on desktop? is it only for mobile?

**Pull request merged**
